In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import seaborn as sns
from scipy import stats
import json
import ast

# Data loading

In [ ]:
df = pd.read_json("/content/preprod-pos-export.json", encoding='iso-8859-1')
bn = pd.DataFrame(df.shops.values.tolist())

# Data Exploration and cleaning in Nested Format

Deleting irrelevant features

In [ ]:
bn_light=bn.drop(bn.columns[-11:],axis=1)
bn_light=bn_light.drop(['arabsoft_interfacing','caisse_actions','deleted_by','caisse_history','printers','users','modifications','tvas','units'],axis=1)
bn_light

Download a spreadsheet of the data

In [ ]:
#bn_light.to_excel("Full_DB_2.xlsx")

# Data Exploration

Viewing shops

In [ ]:
b=df.shops.values.tolist()
b

In [ ]:
df['shops']

In [ ]:
print('bn : ', bn.columns)
print('\n bn_light : ',bn_light.columns)

In [ ]:
bn_light['orders'].isna()

Function to Determine **non NAN** values in a column

In [ ]:
def NonNanValues(DF,columnName):
  L=[]
  for i in range(152) :
    if not (DF[columnName].isna()[i]) :
      L.append(i)
  #print(f' liste : {L}')
  return L

# output : 32 , 107

Non Nan for all columns

In [ ]:
for col in bn_light.columns :
  print(f'{col} : {NonNanValues(bn_light,col)} \n')

Viewing data

In [ ]:
bn_light['deleted_at'][25]
#print(f"{bn_light['deleted_at'][25][c]} \n ")

In [ ]:
for c in bn_light['deliveries'][107].keys() :
  print(f"{bn_light['deliveries'][107][c]} \n ")

In [ ]:
#for c in bn_light['tables'][121].keys() :
  #print(f"{bn_light['tables'][121][c]} \n ")

In [ ]:
for c in bn_light['categories'][121].keys() :
  print(f"{bn_light['categories'][121][c]} \n ")

In [ ]:
#for c in bn_light['a'][10].keys() :
  #print(f"{bn_light['a'][107][c]} \n ")

In [ ]:
for c in bn_light['deliveries'][107].keys() :
  print(f"{bn_light['deliveries'][107][c]} \n ")

In [ ]:
for c in bn_light['pre_orders'][107].keys() :
  print(f"{bn_light['pre_orders'][107][c]} \n ")

In [ ]:
print('\n Number of not NaN values in : \n ')
for col in bn_light.columns :
  #print(f' \n colonne {col} : \n {bn[col]} \n -------------')
  print(f' {col} : {152 - bn_light[col].isna().sum()} \n ')

# 107 Data Exploration

In [ ]:
#for col in bn_light.columns :
  #print(f' column {col} : \n {bn_light[col][107]} \n')
df107 = pd.DataFrame(bn_light.iloc[107])
df107 = df107.drop(['deleted_at','table_spaces','restaurant_tickets','tables','id','deleted'],axis=0)
df107

In [ ]:
df_dict = dict()
for i in df107.index :
  df_dict[i]=list(df107.loc[i])
df_dict.keys()

# 107 DataFrame Denesting

In [ ]:
orders=list(df107.loc['orders'])
len(orders[0]) #538 elements of type dict ::    { id ~ i[0] : dict ~ i[1] }
orders_list=[]
for i in orders[0].items() :
  #print(i)
  orders_list.append([i[0],i[1]]) #  [[id,dict],[id,dict],....]


OL=pd.DataFrame(orders_list,columns=['order_id','data'])
print(type(OL))

### Flatten list

#OL= OL.explode('data')
#OL

orderr=pd.json_normalize(json.loads(OL.to_json(orient="records")))
drop_list=['data.id','data.totalTVA','data.user_id','data.finished_at','data.finished_by','data.payment_methods.offer.payment_method_id',
           'data.payment_methods.livraison.payment_method_id','data.payment_methods.carte_bancaire.payment_method_id','data.payment_methods.cheque.payment_method_id',
           'data.payment_methods.espece.payment_method_id']
orderr = orderr.drop(drop_list,axis=1)
#list(orderr['data.total'])
orderr
#OL['data'][0]

<class 'pandas.core.frame.DataFrame'>

,order_id,data.clientCardNumber,data.coupon,data.date,data.dateToTime,data.delivery,data.emporter,data.note,data.offre,data.orderStatus,...,data.payment_methods.-NaMLl3q3GLq8EWFHaSR.payment_method_id,data.payment_methods.-NaMLl3q3GLq8EWFHaSR.payment_method_name,data.payment_methods.-NaMLl3q3GLq8EWFHaSR.value,data.payment_methods.-NaMLlUmoq63lFBkut1o.payment_method_id,data.payment_methods.-NaMLlUmoq63lFBkut1o.payment_method_name,data.payment_methods.-NaMLlUmoq63lFBkut1o.value,data.payment_methods.-NaMPTDAxIPs6EmM7FK5.payment_method_id,data.payment_methods.-NaMPTDAxIPs6EmM7FK5.payment_method_name,data.payment_methods.-NaMPTDAxIPs6EmM7FK5.value,data.duplicata
0,-NRgZ4MU6Ed_Lz7uB1Er,,0.0,29/03/2023 08:51,1680079866815,False,False,,0.0,NONE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-NRjua5QZerYDHGqnbV9,,0.0,30/03/2023 00:28,1680136099355,False,False,ok,0.0,NONE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-NRjvxkrCBHg8Kddjm8v,,0.0,30/03/2023 00:34,1680136458392,False,False,pp,0.0,NONE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-NRjyJTZLHFf-Amyc9mq,,0.0,30/03/2023 00:44,1680137075715,False,False,,0.0,NONE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,-NRjz3gIgD-AvxJd5iil,,0.0,30/03/2023 00:47,1680137273193,False,False,,0.0,NONE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
533,-NbJzvRrfgWm4hl0sHlI,,0.0,08/08/2023 12:54,1691495676045,True,False,,0.0,NONE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
534,-NbK-27DPVaidt17BpQp,,0.0,08/08/2023 12:55,1691495707495,False,False,,0.0,NONE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
535,-NbK-s5OmMGZuOG4LGjC,,0.0,08/08/2023 12:58,1691495924308,False,False,,0.0,NONE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
536,-NbK0HjWWahaKYxMZmN4,,0.0,08/08/2023 13:00,1691496033435,False,False,,0.0,NONE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
537,-NbK1BjDwUO4VUHmmvNW,,0.0,08/08/2023 13:04,1691496270995,False,False,,0.0,NONE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False

In [ ]:
list(orderr.loc[350])

In [ ]:
order1=orderr[:]

In [ ]:
list(orderr.columns)

In [ ]:
orderr['data.payment_methods.-NYOUBiWRJFrVrNVXmER.payment_method_id']

In [ ]:
orderr['data.payment_methods.-NYOUBiWRJFrVrNVXmER.payment_method_id'].isnull().sum()

In [ ]:
orderr.info()

In [ ]:
orderr.isnull().sum() # output series

In [ ]:
orderr.describe()

,data.coupon,data.dateToTime,data.offre,data.payment_methods.espece.value,data.remise,data.remiseCard,data.ticketNumber,data.total,data.totalOffre,data.totalRemise,...,data.payment_methods.-N_Yu9XBBpYhdNbQ9yih.value,data.payment_methods.-N_Yu8zLHI1J7BXhy9dQ.value,data.payment_methods.-N_Yu8uninowLf_kc5Nz.value,data.payment_methods.-N_Yu9Fd086cdEJJUjJo.value,data.payment_methods.-NaHSICjYhHeqb4GFhoL.value,data.payment_methods.-NaMKfK7JWcnU2DgzLgv.value,data.payment_methods.-NaMKf9_2ENTwOxlemYR.value,data.payment_methods.-NaMLl3q3GLq8EWFHaSR.value,data.payment_methods.-NaMLlUmoq63lFBkut1o.value,data.payment_methods.-NaMPTDAxIPs6EmM7FK5.value
count,538.000000,5.380000e+02,538.000000,390.000000,538.000000,538.0,538.000000,538.000000,538.000000,538.000000,...,1.0,1.0,1.0,1.0,1.0,2.000000,1.0,2.000000,1.0,3.0
mean,0.022119,1.687858e+12,0.160037,21.590990,0.576208,0.0,11.037175,26.681974,0.235316,0.483513,...,1.0,36.0,10.9,37.3,0.0,5.500000,30.0,1.000000,0.0,0.0
std,0.255104,3.222646e+09,0.989169,25.798594,4.652021,0.0,10.335459,90.992149,1.626520,3.201441,...,NaN,NaN,NaN,NaN,NaN,0.707107,NaN,1.414214,NaN,0.0
min,0.000000,1.680080e+12,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,1.0,36.0,10.9,37.3,0.0,5.000000,30.0,0.000000,0.0,0.0
25%,0.000000,1.686673e+12,0.000000,9.000000,0.000000,0.0,3.000000,6.000000,0.000000,0.000000,...,1.0,36.0,10.9,37.3,0.0,5.250000,30.0,0.500000,0.0,0.0
50%,0.000000,1.688730e+12,0.000000,11.000000,0.000000,0.0,8.000000,10.000000,0.000000,0.000000,...,1.0,36.0,10.9,37.3,0.0,5.500000,30.0,1.000000,0.0,0.0
75%,0.000000,1.690462e+12,0.000000,26.025000,0.000000,0.0,16.000000,27.000000,0.000000,0.000000,...,1.0,36.0,10.9,37.3,0.0,5.750000,30.0,1.500000,0.0,0.0
max,4.300000,1.691496e+12,10.000000,201.400000,50.000000,0.0,50.000000,1800.000000,27.000000,27.540000,...,1.0,36.0,10.9,37.3,0.0,6.000000,30.0,2.000000,0.0,0.0

In [ ]:
drop_LL=[]
for i in range(len(orderr.describe().columns)) :
  if (orderr.describe().iloc[1,i] == 0 ) :
    drop_LL.append(orderr.describe().columns[i])

drop_LL

In [ ]:
orderr=orderr.drop(drop_LL,axis=1)
orderr

In [ ]:
orderr.describe()

In [ ]:
orderr.info()

In [ ]:
print('\n Number of not NaN values in : \n ')
for col in orderr.columns :
  print(f' {col} : {538 - orderr[col].isna().sum()} \n ')

In [ ]:
for col in orderr.columns :
  print(f'{col} : {NonNanValues(orderr,col)} \n')

In [ ]:
orderr.to_excel('orders.xlsx', index='False')

# Full DB Treatement

In [ ]:
b1=df.shops.values.tolist()
bn1 = pd.DataFrame(df.shops.values.tolist())['caisse_actions']
bn2 = pd.DataFrame(df.shops.values.tolist())['id']
s2=set(bn2)
len(s2) #151
#len(bn2) #152

151

In [ ]:
nu = [x for x in bn1]
#len(nu) #152
ni = [x for x in bn2]
len(ni)  #152 shops

152

In [ ]:
bn=pd.DataFrame(bn)
bn1=pd.DataFrame(bn1)
bn2=pd.DataFrame(bn2)

In [ ]:
type(bn1.caisse_actions.values)
#bn1.caisse_actions.values

numpy.ndarray

In [ ]:
k1 = bn1.caisse_actions.values.tolist()
kk1=[x for x in k1 if(str(x) != 'nan')]
print(len(k1) - len(kk1))
#for i in k1 :
 # print(i)

2

In [ ]:
k2 = bn1.caisse_actions.values.tolist()
for i in k2[:1] :
  print(k2)

[{'-N0jaJOcB3v614jVTwnD': {'deleted': False, 'flag': 'encaissement', 'id': '-N0jaJOcB3v614jVTwnD', 'name': 'Encaissement', 'order': 1}, '-N0jaJPshr7qKFML4zZ_': {'deleted': False, 'flag': 'decaissement', 'id': '-N0jaJPshr7qKFML4zZ_', 'name': 'Dï¿½caissement', 'order': 2}, '-N0jaJRQhXFI0RpDRVSd': {'deleted': False, 'flag': 'changer_argent', 'id': '-N0jaJRQhXFI0RpDRVSd', 'name': "Changer de l'argent", 'order': 0}}, {'-MwkV1eVK3geg7VPa08C': {'deleted': False, 'flag': 'encaissement', 'id': '-MwkV1eVK3geg7VPa08C', 'name': 'Encaissement', 'order': 1}, '-MwkV1fwWXIWD5WrVVTI': {'deleted': False, 'flag': 'decaissement', 'id': '-MwkV1fwWXIWD5WrVVTI', 'name': 'Dï¿½caissement', 'order': 2}, '-MwkV1h_pj0X_njgPOYm': {'deleted': False, 'flag': 'changer_argent', 'id': '-MwkV1h_pj0X_njgPOYm', 'name': "Changer de l'argent", 'order': 0}}, {'-N1I9isxVV0mOYVACPzg': {'deleted': False, 'flag': 'encaissement', 'id': '-N1I9isxVV0mOYVACPzg', 'name': 'Encaissement', 'order': 1}, '-N1I9iuR5p_9Z9w7iHlH': {'deleted': False, 'flag': 'decaissement', 'id': '-N1I9iuR5p_9Z9w7iHlH', 'name': 'Dï¿½caissement', 'order': 2}, '-N1I9j-fFQp47nb078LB': {'deleted': False, 'flag': 'changer_argent', 'id': '-N1I9j-fFQp47nb078LB', 'name': "Changer de l'argent", 'order': 0}}, {'-MySUwhVvChm4ymlAg09': {'deleted': False, 'flag': 'encaissement', 'id': '-MySUwhVvChm4ymlAg09', 'name': 'Encaissement', 'order': 1}, '-MySUwjC3GwiGCUmNYTR': {'deleted': False, 'flag': 'decaissement', 'id': '-MySUwjC3GwiGCUmNYTR', 'name': 'Dï¿½caissement', 'order': 2}, '-MySUwkmdJDPxhXeIPgV': {'deleted': False, 'flag': 'changer_argent', 'id': '-MySUwkmdJDPxhXeIPgV', 'name': "Changer de l'argent", 'order': 0}}, {'-N2R7RxiS-f0NK74jGwA': {'deleted': False, 'flag': 'encaissement', 'id': '-N2R7RxiS-f0NK74jGwA', 'name': 'Encaissement', 'order': 1}, '-N2R7RzQ-fZoM7tmEwCL': {'deleted': False, 'flag': 'decaissement', 'id': '-N2R7RzQ-fZoM7tmEwCL', 'name': 'Dï¿½caissement', 'order': 2}, '-N2R7S-hjsyXmwPOq03_': {'deleted': False, 'flag': 'changer_argent', 'id': '-N2R7S-hjsyXmwPOq03_', 'name': "Changer de l'argent", 'order': 0}}, {'-MqyFBv60F1XiqfeJkTl': {'deleted': False, 'flag': 'encaissement', 'id': '-MqyFBv60F1XiqfeJkTl', 'name': 'Encaissement', 'order': 1}, '-MqyFBwnuC1sGntIgfs8': {'deleted': False, 'flag': 'decaissement', 'id': '-MqyFBwnuC1sGntIgfs8', 'name': 'Dï¿½caissement', 'order': 2}, '-MqyFByzONAQHzsp2dJT': {'deleted': False, 'flag': 'changer_argent', 'id': '-MqyFByzONAQHzsp2dJT', 'name': "Changer de l'argent", 'order': 0}}, nan, {'-Mcyp4CrqZy4ca99-qTD': {'deleted': False, 'flag': 'encaissement', 'id': '-Mcyp4CrqZy4ca99-qTD', 'name': 'Encaissement', 'order': 1}, '-Mcyp4EzWk-8IqNPWTw6': {'deleted': False, 'flag': 'decaissement', 'id': '-Mcyp4EzWk-8IqNPWTw6', 'name': 'Dï¿½caissement', 'order': 2}, '-Mcyp4Gmrz-uGJNNzs6X': {'deleted': False, 'flag': 'changer_argent', 'id': '-Mcyp4Gmrz-uGJNNzs6X', 'name': "Changer de l'argent", 'order': 0}}, {'-N4hRAVD896J7l6-7TjP': {'deleted': False, 'flag': 'encaissement', 'id': '-N4hRAVD896J7l6-7TjP', 'name': 'Encaissement', 'order': 1}, '-N4hRAWdDoDDPSNTbALZ': {'deleted': False, 'flag': 'decaissement', 'id': '-N4hRAWdDoDDPSNTbALZ', 'name': 'Dï¿½caissement', 'order': 2}, '-N4hRAYBOkaNYiQfDvVH': {'deleted': False, 'flag': 'changer_argent', 'id': '-N4hRAYBOkaNYiQfDvVH', 'name': "Changer de l'argent", 'order': 0}}, {'-MwaGsIsOC39Imt-olX-': {'deleted': False, 'flag': 'encaissement', 'id': '-MwaGsIsOC39Imt-olX-', 'name': 'Encaissement', 'order': 1}, '-MwaGsKQGbAKeKKqDFmN': {'deleted': False, 'flag': 'decaissement', 'id': '-MwaGsKQGbAKeKKqDFmN', 'name': 'Dï¿½caissement', 'order': 2}, '-MwaGsMJ71VDNG2CjnoC': {'deleted': False, 'flag': 'changer_argent', 'id': '-MwaGsMJ71VDNG2CjnoC', 'name': "Changer de l'argent", 'order': 0}}, {'-Me5V5sYKVAtT5wOqyLS': {'deleted': False, 'flag': 'encaissement', 'id': '-Me5V5sYKVAtT5wOqyLS', 'name': 'Encaissement', 'order': 1}, '-Me5V5u23awy8rZVPPuq': {'deleted': False, 'flag': 'decaissement', 'id': '-Me5V5u23awy8rZVPPuq', 'name': 'Dï¿½caissement', 'order': 2}, '-Me5V5vZYqE_DeYF2b0o': {'deleted': False, 'flag': 'changer_argent', 'id': '-Me5V5vZYqE_DeYF2b0o', 'name': "Changer de l'argent", 'order': 0}}, {'-N-w4FXhgwn88Av5iLv2': {'deleted': False, 'flag': 'encaissement', 'id': '-N-w4FXhgwn88Av5iLv2', 'name': 'Encaissement', 'order': 1}, '-N-w4FZYp4kb3P9n75gf': {'deleted': False, 'flag': 'decaissement', 'id': '-N-w4FZYp4kb3P9n75gf', 'name': 'Dï¿½caissement', 'order': 2}, '-N-w4FaGJMvhokF7IBkb': {'deleted': False, 'flag': 'changer_argent', 'id': '-N-w4FaGJMvhokF7IBkb', 'name': "Changer de l'argent", 'order': 0}}, {'-MnPriRtV5eWYzE_OAVZ': {'deleted': False, 'flag': 'encaissement', 'id': '-MnPriRtV5eWYzE_OAVZ', 'name': 'Encaissement', 'order': 1}, '-MnPriU1vPyckCo3Nc4e': {'deleted': False, 'flag': 'decaissement', 'id': '-MnPriU1vPyckCo3Nc4e', 'name': 'Dï¿½caissement', 'order': 2}, '-MnPriVtVnSJJP8y_v2Y': {'deleted': False, 'flag': 'changer_argent', 'id': '-MnPriVtVnSJJP8y_v2Y', 'name': "Changer de l'argent", 'order': 0}}, {'-McV0jkaW1X-DmIhbZ80': {'deleted': False, 'flag': 'encaissement', 'id': '-McV0jkaW1X-DmIhbZ80', 'name': 'Encaissement', 'order': 1}, '-McV0jmRgtIhg0DhHRni': {'deleted': False, 'flag': 'decaissement', 'id': '-McV0jmRgtIhg0DhHRni', 'name': 'Dï¿½caissement', 'order': 2}, '-McV0jnva_S47RgtDSDD': {'deleted': False, 'flag': 'changer_argent', 'id': '-McV0jnva_S47RgtDSDD', 'name': "Changer de l'argent", 'order': 0}}, {'-Mgfy3bGMqOgo7-yeo-c': {'deleted': False, 'flag': 'encaissement', 'id': '-Mgfy3bGMqOgo7-yeo-c', 'name': 'Encaissement', 'order': 1}, '-Mgfy3cvzFEIaudbAeRF': {'deleted': False, 'flag': 'decaissement', 'id': '-Mgfy3cvzFEIaudbAeRF', 'name': 'Dï¿½caissement', 'order': 2}, '-Mgfy3eQDMVblUUGqHKW': {'deleted': False, 'flag': 'changer_argent', 'id': '-Mgfy3eQDMVblUUGqHKW', 'name': "Changer de l'argent", 'order': 0}}, {'-Mdq9lNl1r2CWg1oejr1': {'deleted': False, 'flag': 'encaissement', 'id': '-Mdq9lNl1r2CWg1oejr1', 'name': 'Encaissement', 'order': 1}, '-Mdq9lPF3XD-pPFGove3': {'deleted': False, 'flag': 'decaissement', 'id': '-Mdq9lPF3XD-pPFGove3', 'name': 'Dï¿½caissement', 'order': 2}, '-Mdq9lRWtRV3s41iZPNl': {'deleted': False, 'flag': 'changer_argent', 'id': '-Mdq9lRWtRV3s41iZPNl', 'name': "Changer de l'argent", 'order': 0}}, {'-MaHwuHFMtM6ecvJmLWT': {'deleted': False, 'flag': 'encaissement', 'id': '-MaHwuHFMtM6ecvJmLWT', 'name': 'Encaissement', 'order': 1}, '-MaHwuL2YL4Fku6NMhYL': {'deleted': False, 'flag': 'decaissement', 'id': '-MaHwuL2YL4Fku6NMhYL', 'name': 'Dï¿½caissement', 'order': 2}, '-MaHwuQ0qLTzr1y8QXRy': {'deleted': False, 'flag': 'changer_argent', 'id': '-MaHwuQ0qLTzr1y8QXRy', 'name': "Changer de l'argent", 'order': 0}}, {'-McSlSpbfgweHrEjxkCY': {'deleted': False, 'flag': 'encaissement', 'id': '-McSlSpbfgweHrEjxkCY', 'name': 'Encaissement', 'order': 1}, '-McSlSrKhLtnKMpEkMAX': {'deleted': False, 'flag': 'decaissement', 'id': '-McSlSrKhLtnKMpEkMAX', 'name': 'Dï¿½caissement', 'order': 2}, '-McSlSsvhfEMLyqwoxn1': {'deleted': False, 'flag': 'changer_argent', 'id': '-McSlSsvhfEMLyqwoxn1', 'name': "Changer de l'argent", 'order': 0}}, {'-MliYHczEN5GTAV3u8vw': {'deleted': False, 'flag': 'encaissement', 'id': '-MliYHczEN5GTAV3u8vw', 'name': 'Encaissement', 'order': 1}, '-MliYHePWaUoEPTLkZ5_': {'deleted': False, 'flag': 'decaissement', 'id': '-MliYHePWaUoEPTLkZ5_', 'name': 'Dï¿½caissement', 'order': 2}, '-MliYHlDNHNaY_kgN6xv': {'deleted': False, 'flag': 'changer_argent', 'id': '-MliYHlDNHNaY_kgN6xv', 'name': "Changer de l'argent", 'order': 0}}, {'-McV0a5-etNL4MauiQQ7': {'deleted': False, 'flag': 'encaissement', 'id': '-McV0a5-etNL4MauiQQ7', 'name': 'Encaissement', 'order': 1}, '-McV0a6xGx0XC0Q31gS8': {'deleted': False, 'flag': 'decaissement', 'id': '-McV0a6xGx0XC0Q31gS8', 'name': 'Dï¿½caissement', 'order': 2}, '-McV0a8dK7QhD752lugO': {'deleted': False, 'flag': 'changer_argent', 'id': '-McV0a8dK7QhD752lugO', 'name': "Changer de l'argent", 'order': 0}}, {'-Mx-HGAlE5iemUn5FFk-': {'deleted': False, 'flag': 'encaissement', 'id': '-Mx-HGAlE5iemUn5FFk-', 'name': 'Encaissement', 'order': 1}, '-Mx-HGCQfWGjhfNHau9b': {'deleted': False, 'flag': 'decaissement', 'id': '-Mx-HGCQfWGjhfNHau9b', 'name': 'Dï¿½caissement', 'order': 2}, '-Mx-HGE5vwoB1HmcaEb-': {'deleted': False, 'flag': 'changer_argent', 'id': '-Mx-HGE5vwoB1HmcaEb-', 'name': "Changer de l'argent", 'order': 0}}, {'-N4RNlbtNneP5Z5ktEwO': {'deleted': False, 'flag': 'encaissement', 'id': '-N4RNlbtNneP5Z5ktEwO', 'name': 'Encaissement', 'order': 1}, '-N4RNldBkI2aGRNOsG4P': {'deleted': False, 'flag': 'decaissement', 'id': '-N4RNldBkI2aGRNOsG4P', 'name': 'Dï¿½caissement', 'order': 2}, '-N4RNlf4zObRJuhasLrT': {'deleted': False, 'flag': 'changer_argent', 'id': '-N4RNlf4zObRJuhasLrT', 'name': "Changer de l'argent", 'order': 0}}, {'-MvbbCjhDb6cZ4pKAyBK': {'deleted': False, 'flag': 'encaissement', 'id': '-MvbbCjhDb6cZ4pKAyBK', 'name': 'Encaissement', 'order': 1}, '-MvbbClHHSiRQdNpG-jS': {'deleted': False, 'flag': 'decaissement', 'id': '-MvbbClHHSiRQdNpG-jS', 'name': 'Dï¿½caissement', 'order': 2}, '-MvbbCmi3-HNQxVzjlgA': {'deleted': False, 'flag': 'changer_argent', 'id': '-MvbbCmi3-HNQxVzjlgA', 'name': "Changer de l'argent", 'order': 0}}, {'-MblCph6aWSbttg1VsHP': {'deleted': False, 'flag': 'encaissement', 'id': '-MblCph6aWSbttg1VsHP', 'name': 'Encaissement', 'order': 1}, '-MblCpkotaxzTA-ONLZT': {'deleted': False, 'flag': 'decaissement', 'id': '-MblCpkotaxzTA-ONLZT', 'name': 'Dï¿½caissement', 'order': 2}, '-MblCpnQENhTxEfUaDb6': {'deleted': False, 'flag': 'changer_argent', 'id': '-MblCpnQENhTxEfUaDb6', 'name': "Changer de l'argent", 'order': 0}}, {'-MygqoPjwUB5HL-dWt4R': {'deleted': False, 'flag': 'encaissement', 'id': '-MygqoPjwUB5HL-dWt4R', 'name': 'Encaissement', 'order': 1}, '-MygqoRRq5A_fOHAeqaf': {'deleted': False, 'flag': 'decaissement', 'id': '-MygqoRRq5A_fOHAeqaf', 'name': 'Dï¿½caissement', 'order': 2}, '-MygqoT9NKXVV2Dx_u7n': {'deleted': False, 'flag': 'changer_argent', 'id': '-MygqoT9NKXVV2Dx_u7n', 'name': "Changer de l'argent", 'order': 0}}, {'-McV0gdPFrSwYj-U7yNZ': {'deleted': False, 'flag': 'encaissement', 'id': '-McV0gdPFrSwYj-U7yNZ', 'name': 'Encaissement', 'order': 1}, '-McV0gerHXTIAfkuQ_cc': {'deleted': False, 'flag': 'decaissement', 'id': '-McV0gerHXTIAfkuQ_cc', 'name': 'Dï¿½caissement', 'order': 2}, '-McV0ggmOzR7zcKPrbPb': {'deleted': False, 'flag': 'changer_argent', 'id': '-McV0ggmOzR7zcKPrbPb', 'name': "Changer de l'argent", 'order': 0}}, {'-McV-wybMSoxvnxo9yq6': {'deleted': False, 'flag': 'encaissement', 'id': '-McV-wybMSoxvnxo9yq6', 'name': 'Encaissement', 'order': 1}, '-McV-x-L9YY-Xesjf45c': {'deleted': False, 'flag': 'decaissement', 'id': '-McV-x-L9YY-Xesjf45c', 'name': 'Dï¿½caissement', 'order': 2}, '-McV-x0uWCFCkpRXLTdy': {'deleted': False, 'flag': 'changer_argent', 'id': '-McV-x0uWCFCkpRXLTdy', 'name': "Changer de l'argent", 'order': 0}}, {'-N0jVyanGxtVIgpnMLU4': {'deleted': False, 'flag': 'encaissement', 'id': '-N0jVyanGxtVIgpnMLU4', 'name': 'Encaissement', 'order': 1}, '-N0jVycJcllNIA6sTwG5': {'deleted': False, 'flag': 'decaissement', 'id': '-N0jVycJcllNIA6sTwG5', 'name': 'Dï¿½caissement', 'order': 2}, '-N0jVydap_VWLdAiEFmQ': {'deleted': False, 'flag': 'changer_argent', 'id': '-N0jVydap_VWLdAiEFmQ', 'name': "Changer de l'argent", 'order': 0}}, {'-MkrLLE9GtgE2AtwvKL3': {'deleted': False, 'flag': 'encaissement', 'id': '-MkrLLE9GtgE2AtwvKL3', 'name': 'Encaissement', 'order': 1}, '-MkrLLFu3jB7SyVbskfq': {'deleted': False, 'flag': 'decaissement', 'id': '-MkrLLFu3jB7SyVbskfq', 'name': 'Dï¿½caissement', 'order': 2}, '-MkrLLHSwLykmbqI_1gt': {'deleted': False, 'flag': 'changer_argent', 'id': '-MkrLLHSwLykmbqI_1gt', 'name': "Changer de l'argent", 'order': 0}}, {'-MuGE4W0xgUOBZmRRTet': {'deleted': False, 'flag': 'encaissement', 'id': '-MuGE4W0xgUOBZmRRTet', 'name': 'Encaissement', 'order': 1}, '-MuGE4XgVvQDKgMirenY': {'deleted': False, 'flag': 'decaissement', 'id': '-MuGE4XgVvQDKgMirenY', 'name': 'Dï¿½caissement', 'order': 2}, '-MuGE4ZN4OnVano5G3kG': {'deleted': False, 'flag': 'changer_argent', 'id': '-MuGE4ZN4OnVano5G3kG', 'name': "Changer de l'argent", 'order': 0}}, {'-Ma9Xd4nSgVIbeosmc3x': {'deleted': False, 'flag': 'encaissement', 'id': '-Ma9Xd4nSgVIbeosmc3x', 'name': 'Encaissement', 'order': 1}, '-Ma9XdC2A2S2ves_cO0_': {'deleted': False, 'flag': 'decaissement', 'id': '-Ma9XdC2A2S2ves_cO0_', 'name': 'Dï¿½caissement', 'order': 2}, '-Ma9XdLW6wdmv51EUY6r': {'deleted': False, 'flag': 'changer_argent', 'id': '-Ma9XdLW6wdmv51EUY6r', 'name': "Changer de l'argent", 'order': 0}}, {'-Mmvb7X9mHK1r21Zm0g-': {'deleted': False, 'flag': 'encaissement', 'id': '-Mmvb7X9mHK1r21Zm0g-', 'name': 'Encaissement', 'order': 1}, '-Mmvb7YiOf6zBePMpZu4': {'deleted': False, 'flag': 'decaissement', 'id': '-Mmvb7YiOf6zBePMpZu4', 'name': 'Dï¿½caissement', 'order': 2}, '-Mmvb7_K6NCcQSShKMZF': {'deleted': False, 'flag': 'changer_argent', 'id': '-Mmvb7_K6NCcQSShKMZF', 'name': "Changer de l'argent", 'order': 0}}, {'-N9VYIhIcUrI-QCW7lXf': {'deleted': False, 'flag': 'encaissement', 'id': '-N9VYIhIcUrI-QCW7lXf', 'name': 'Encaissement', 'order': 1}, '-N9VYIlkvOBE9IcvtffY': {'deleted': False, 'flag': 'decaissement', 'id': '-N9VYIlkvOBE9IcvtffY', 'name': 'Dï¿½caissement', 'order': 2}, '-N9VYIqG5GSorDe7CHfB': {'deleted': False, 'flag': 'changer_argent', 'id': '-N9VYIqG5GSorDe7CHfB', 'name': "Changer de l'argent", 'order': 0}}, {'-McV04OUWoG1uzT9NpqA': {'deleted': False, 'flag': 'encaissement', 'id': '-McV04OUWoG1uzT9NpqA', 'name': 'Encaissement', 'order': 1}, '-McV04Pzsq1jwynuKkWR': {'deleted': False, 'flag': 'decaissement', 'id': '-McV04Pzsq1jwynuKkWR', 'name': 'Dï¿½caissement', 'order': 2}, '-McV04RXJR6gNDAIhNKW': {'deleted': False, 'flag': 'changer_argent', 'id': '-McV04RXJR6gNDAIhNKW', 'name': "Changer de l'argent", 'order': 0}}, {'-NOKAWqerA3eqf3eUP67': {'deleted': False, 'flag': 'encaissement', 'id': '-NOKAWqerA3eqf3eUP67', 'name': 'Encaissement', 'order': 1}, '-NOKAWvQhvoiZJ-AwhlS': {'deleted': False, 'flag': 'decaissement', 'id': '-NOKAWvQhvoiZJ-AwhlS', 'name': 'Dï¿½caissement', 'order': 2}, '-NOKAX--46TtFvlzK_WX': {'deleted': False, 'flag': 'changer_argent', 'id': '-NOKAX--46TtFvlzK_WX', 'name': "Changer de l'argent", 'order': 0}}, {'-Mj8r114dMh_qZN7ZZ_2': {'deleted': False, 'flag': 'encaissement', 'id': '-Mj8r114dMh_qZN7ZZ_2', 'name': 'Encaissement', 'order': 1}, '-Mj8r12vWGK1AaJHmS3S': {'deleted': False, 'flag': 'decaissement', 'id': '-Mj8r12vWGK1AaJHmS3S', 'name': 'Dï¿½caissement', 'order': 2}, '-Mj8r14wUZzIIBpO8-SV': {'deleted': False, 'flag': 'changer_argent', 'id': '-Mj8r14wUZzIIBpO8-SV', 'name': "Changer de l'argent", 'order': 0}}, {'-NLL4zr_bRpeXwIl-PPB': {'deleted': False, 'flag': 'encaissement', 'id': '-NLL4zr_bRpeXwIl-PPB', 'name': 'Encaissement', 'order': 1}, '-NLL4zw2AgotAEHWW-7C': {'deleted': False, 'flag': 'decaissement', 'id': '-NLL4zw2AgotAEHWW-7C', 'name': 'Dï¿½caissement', 'order': 2}, '-NLL5--ODigXwehZguba': {'deleted': False, 'flag': 'changer_argent', 'id': '-NLL5--ODigXwehZguba', 'name': "Changer de l'argent", 'order': 0}}, {'-McTa__ie1ML10jQHiQD': {'deleted': False, 'flag': 'encaissement', 'id': '-McTa__ie1ML10jQHiQD', 'name': 'Encaissement', 'order': 1}, '-McTa_bZ4whEIqPK7bqh': {'deleted': False, 'flag': 'decaissement', 'id': '-McTa_bZ4whEIqPK7bqh', 'name': 'Dï¿½caissement', 'order': 2}, '-McTa_dACyjAnrEq9Pzi': {'deleted': False, 'flag': 'changer_argent', 'id': '-McTa_dACyjAnrEq9Pzi', 'name': "Changer de l'argent", 'order': 0}}, {'-McV19fRGVtFi4pQxCbe': {'deleted': False, 'flag': 'encaissement', 'id': '-McV19fRGVtFi4pQxCbe', 'name': 'Encaissement', 'order': 1}, '-McV19gkbOLzvV5Pt7lJ': {'deleted': False, 'flag': 'decaissement', 'id': '-McV19gkbOLzvV5Pt7lJ', 'name': 'Dï¿½caissement', 'order': 2}, '-McV19iAkJH0-xaxktmw': {'deleted': False, 'flag': 'changer_argent', 'id': '-McV19iAkJH0-xaxktmw', 'name': "Changer de l'argent", 'order': 0}}, {'-NLeFRv20K7NT_D0_yup': {'deleted': False, 'flag': 'encaissement', 'id': '-NLeFRv20K7NT_D0_yup', 'name': 'Encaissement', 'order': 1}, '-NLeFRzUDTmqfXyl3SGU': {'deleted': False, 'flag': 'decaissement', 'id': '-NLeFRzUDTmqfXyl3SGU', 'name': 'Dï¿½caissement', 'order': 2}, '-NLeFS3LoDt9_DyMCtTi': {'deleted': False, 'flag': 'changer_argent', 'id': '-NLeFS3LoDt9_DyMCtTi', 'name': "Changer de l'argent", 'order': 0}}, {'-McV-QYBtg9E3K52LmCS': {'deleted': False, 'flag': 'encaissement', 'id': '-McV-QYBtg9E3K52LmCS', 'name': 'Encaissement', 'order': 1}, '-McV-QZiEUlhRmMZ3c5M': {'deleted': False, 'flag': 'decaissement', 'id': '-McV-QZiEUlhRmMZ3c5M', 'name': 'Dï¿½caissement', 'order': 2}, '-McV-QaZrJLBOnhyUFTe': {'deleted': False, 'flag': 'changer_argent', 'id': '-McV-QaZrJLBOnhyUFTe', 'name': "Changer de l'argent", 'order': 0}}, {'-MoXcs-sY2O0Ar6SBxWG': {'deleted': False, 'flag': 'encaissement', 'id': '-MoXcs-sY2O0Ar6SBxWG', 'name': 'Encaissement', 'order': 1}, '-MoXcs1rK2LFoDBCVQoc': {'deleted': False, 'flag': 'decaissement', 'id': '-MoXcs1rK2LFoDBCVQoc', 'name': 'Dï¿½caissement', 'order': 2}, '-MoXcs3eTJ0hFx3biRUm': {'deleted': False, 'flag': 'changer_argent', 'id': '-MoXcs3eTJ0hFx3biRUm', 'name': "Changer de l'argent", 'order': 0}}, {'-MsV52Em9axAB4RL9IV3': {'deleted': False, 'flag': 'encaissement', 'id': '-MsV52Em9axAB4RL9IV3', 'name': 'Encaissement', 'order': 1}, '-MsV52GdV6U5B7PIw0B0': {'deleted': False, 'flag': 'decaissement', 'id': '-MsV52GdV6U5B7PIw0B0', 'name': 'Dï¿½caissement', 'order': 2}, '-MsV52IQhMzcX427HNOb': {'deleted': False, 'flag': 'changer_argent', 'id': '-MsV52IQhMzcX427HNOb', 'name': "Changer de l'argent", 'order': 0}}, {'-N6O9DIewpxkx20YZEO5': {'deleted': False, 'flag': 'encaissement', 'id': '-N6O9DIewpxkx20YZEO5', 'name': 'Encaissement', 'order': 1}, '-N6O9DK5jvTT5LhS0fCN': {'deleted': False, 'flag': 'decaissement', 'id': '-N6O9DK5jvTT5LhS0fCN', 'name': 'Dï¿½caissement', 'order': 2}, '-N6O9DLbXGfS31GYJvEm': {'deleted': False, 'flag': 'changer_argent', 'id': '-N6O9DLbXGfS31GYJvEm', 'name': "Changer de l'argent", 'order': 0}}, {'-McV0H9ZMYQAsEWCVU4M': {'deleted': False, 'flag': 'encaissement', 'id': '-McV0H9ZMYQAsEWCVU4M', 'name': 'Encaissement', 'order': 1}, '-McV0HBeekvCIqk52S0b': {'deleted': False, 'flag': 'decaissement', 'id': '-McV0HBeekvCIqk52S0b', 'name': 'Dï¿½caissement', 'order': 2}, '-McV0HD2wM5neUE9Abci': {'deleted': False, 'flag': 'changer_argent', 'id': '-McV0HD2wM5neUE9Abci', 'name': "Changer de l'argent", 'order': 0}}, {'-N0pQU-RRY5i1b-YKXad': {'deleted': False, 'flag': 'encaissement', 'id': '-N0pQU-RRY5i1b-YKXad', 'name': 'Encaissement', 'order': 1}, '-N0pQU0zsxOK2vLlQJ50': {'deleted': False, 'flag': 'decaissement', 'id': '-N0pQU0zsxOK2vLlQJ50', 'name': 'Dï¿½caissement', 'order': 2}, '-N0pQU2FhrX1H6df27Pv': {'deleted': False, 'flag': 'changer_argent', 'id': '-N0pQU2FhrX1H6df27Pv', 'name': "Changer de l'argent", 'order': 0}}, {'-Mcyp9lSdXOCjpaaQhSH': {'deleted': False, 'flag': 'encaissement', 'id': '-Mcyp9lSdXOCjpaaQhSH', 'name': 'Encaissement', 'order': 1}, '-Mcyp9mrVphjItoygHFj': {'deleted': False, 'flag': 'decaissement', 'id': '-Mcyp9mrVphjItoygHFj', 'name': 'Dï¿½caissement', 'order': 2}, '-Mcyp9oJk1_ftLRf_nRz': {'deleted': False, 'flag': 'changer_argent', 'id': '-Mcyp9oJk1_ftLRf_nRz', 'name': "Changer de l'argent", 'order': 0}}, {'-N0VDudG9qujH5Lgc8fN': {'deleted': False, 'flag': 'encaissement', 'id': '-N0VDudG9qujH5Lgc8fN', 'name': 'Encaissement', 'order': 1}, '-N0VDueySgGji2N38cu4': {'deleted': False, 'flag': 'decaissement', 'id': '-N0VDueySgGji2N38cu4', 'name': 'Dï¿½caissement', 'order': 2}, '-N0VDugZ8VnWCVTl-FJP': {'deleted': False, 'flag': 'changer_argent', 'id': '-N0VDugZ8VnWCVTl-FJP', 'name': "Changer de l'argent", 'order': 0}}, {'-Meee5RTb0cmd8rE105e': {'deleted': False, 'flag': 'encaissement', 'id': '-Meee5RTb0cmd8rE105e', 'name': 'Encaissement', 'order': 1}, '-Meee5TIvZUgvadXDhvN': {'deleted': False, 'flag': 'decaissement', 'id': '-Meee5TIvZUgvadXDhvN', 'name': 'Dï¿½caissement', 'order': 2}, '-Meee5VSI5xSiAXIVkV4': {'deleted': False, 'flag': 'changer_argent', 'id': '-Meee5VSI5xSiAXIVkV4', 'name': "Changer de l'argent", 'order': 0}}, {'-McIiI6R5kgRtUJgS3jE': {'deleted': False, 'flag': 'encaissement', 'id': 

In [ ]:
#bnn1 = pd.DataFrame(k1)

In [ ]:
pd.DataFrame.from_records(bn_light).head()

,canceled_orders,categories,deleted,id,info,payment_methods,ingredients,coupons,suppliers,canceled_deliveries,clients,deleted_at,deliveries,pre_orders,table_spaces,restaurant_tickets,tables,orders
0,{'-N1s7krGSiw3iirC7SO1': {'clientCardNumber': ...,{'-N1n9ZCtzZCaw_MeqXHQ': {'childrens': {'-N1nA...,False,1LeuTEU1OaTbPIDjbkfa2LdHJ2m2,"{'dailyRevenue': 0, 'date_reinit_ticket': '13/...","{'-N0k-F2IYa7thOPMIRDw': {'deleted': False, 'f...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,{'-MwzWeQmvpJKjT4VuFb_': {'clientCardNumber': ...,{'-Mwkj0m3_2okSIoaBXKR': {'childrens': {'-Mwkj...,False,1YUuyZj3vaguDV6kniXkjZHGsVJ3,"{'dailyRevenue': 0, 'date_reinit_ticket': '13/...","{'-Mxy9V6mj1oRJFpwkZ6r': {'deleted': False, 'f...","{'-MwlmV_7V3mfko8jej6M': {'deleted': False, 'i...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,{'-N1UgjHZLmAy8iYuQ_Q5': {'clientCardNumber': ...,{'-N1IEOmIQwiFulbgOKXh': {'childrens': {'-N1IE...,False,1fdugKSBzPdBlloqLvtlzHhfKZ22,"{'dailyRevenue': 0, 'date_reinit_ticket': '14/...","{'-N1IC_z42wc2Vke7HZCv': {'deleted': False, 'f...","{'-N1wI5auXRQK1hUlVfrg': {'deleted': True, 'de...",{'-N6lCvvlp_mvbDAA5iB7': {'date': '12/07/2022 ...,"{'-N1rkKxx8ygXt3mtGDXB': {'deleted': False, 'i...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,{'-MySi4uCUuSdtQiwBZ1n': {'clientCardNumber': ...,{'-MySW43ODrka1NVahmZX': {'childrens': {'-MySW...,True,1lHIQ4SKtgdB097iGGt2cSiNxr92,"{'dailyRevenue': 0, 'date_reinit_ticket': '24/...","{'-MySiCIMNni6Pw2lca9g': {'deleted': False, 'f...","{'-MySVRsbkp_8M4_zkBkV': {'deleted': False, 'i...",NaN,NaN,"{'-MySkJwfPBWbrObi-ACO': {'etatCommande': '0',...",{'-MySiXTzhCsFKqLeCxe0': {'addresses': {'-MySi...,24-03-2022,"{'-MySiXtnYvra1ZUbAu6D': {'etatCommande': '2',...",NaN,NaN,NaN,NaN,NaN
4,{'-N2SEdRz55WtMqaCWAIO': {'clientCardNumber': ...,{'-N2R8XD0SR6AkliEjkQx': {'childrens': {'-N2R9...,False,1wkiFE5YD3fxqTICRHJyGRoCs3k2,"{'dailyRevenue': 0, 'date_reinit_ticket': '14/...","{'-N2R7fCL-3pdBNVcpJx1': {'deleted': False, 'f...",NaN,{'-N5nVL9LV2tfb1Gmqb2Q': {'date': '30/06/2022 ...,NaN,NaN,NaN,NaN,NaN,{'-N2R7xmM8lnni_ElGg-7': {'-N2R7xmM8lnni_ElGg-...,NaN,NaN,NaN,NaN

In [ ]:
#pd.json_normalize(bn1).head()

In [ ]:
(bn_light==-1).sum()

canceled_orders        0
categories             0
deleted                0
id                     0
info                   0
payment_methods        0
ingredients            0
coupons                0
suppliers              0
canceled_deliveries    0
clients                0
deleted_at             0
deliveries             0
pre_orders             0
table_spaces           0
restaurant_tickets     0
tables                 0
orders                 0
dtype: int64

# Full DB DeNesting

Importing lightened Full DB of all Startup clients

In [ ]:
DB = pd.read_excel("/content/Full_DB_light.xlsx")

In [ ]:
DB = DB.rename(columns={"Unnamed: 0" : "index"})
DB

,index,id,deleted,deleted_at,info,suppliers,clients,canceled_deliveries,deliveries,pre_orders
0,0,1LeuTEU1OaTbPIDjbkfa2LdHJ2m2,0.0,NaN,"{'dailyRevenue': 0, 'date_reinit_ticket': '13/...",NaN,NaN,NaN,NaN,NaN
1,1,1YUuyZj3vaguDV6kniXkjZHGsVJ3,0.0,NaN,"{'dailyRevenue': 0, 'date_reinit_ticket': '13/...",NaN,NaN,NaN,NaN,NaN
2,2,1fdugKSBzPdBlloqLvtlzHhfKZ22,0.0,NaN,"{'dailyRevenue': 0, 'date_reinit_ticket': '14/...","{'-N1rkKxx8ygXt3mtGDXB': {'deleted': False, 'i...",NaN,NaN,NaN,NaN
3,3,1lHIQ4SKtgdB097iGGt2cSiNxr92,1.0,24-03-2022,"{'dailyRevenue': 0, 'date_reinit_ticket': '24/...",NaN,{'-MySiXTzhCsFKqLeCxe0': {'addresses': {'-MySi...,"{'-MySkJwfPBWbrObi-ACO': {'etatCommande': '0',...","{'-MySiXtnYvra1ZUbAu6D': {'etatCommande': '2',...",NaN
4,4,1wkiFE5YD3fxqTICRHJyGRoCs3k2,0.0,NaN,"{'dailyRevenue': 0, 'date_reinit_ticket': '14/...",NaN,NaN,NaN,NaN,{'-N2R7xmM8lnni_ElGg-7': {'-N2R7xmM8lnni_ElGg-...
...,...,...,...,...,...,...,...,...,...,...
147,147,yPFnCPwL8dNnIvz0PzbKRwUOAfF2,1.0,27-12-2021,"{'date_reinit_ticket': '03/08/2021', 'has_tabl...",NaN,NaN,NaN,NaN,NaN
148,148,yrtyvXC2bkVtAW6REaBy1MRMUg73,0.0,NaN,"{'dailyRevenue': 0, 'date_reinit_ticket': '13/...",NaN,NaN,NaN,NaN,{'-N4hpFYoG1AuHcEJPnRj': {'-N4hpFYoG1AuHcEJPnR...
149,149,ywAv0kkVVifXpe108MhktRUePUH3,1.0,27-12-2021,"{'dailyRevenue': 0, 'date_reinit_ticket': '29/...",NaN,NaN,NaN,NaN,NaN
150,150,z6g3Pjyf6PPLhQb9XhUg7JOeoty2,0.0,NaN,"{'currency': 'TND', 'date_reinit_ticket': '07/...",NaN,NaN,NaN,NaN,NaN
151,151,zNRmMJOGbre7RoMLaE5vDjvWVmm1,0.0,NaN,"{'dailyRevenue': 0, 'date_reinit_ticket': '08/...",NaN,NaN,NaN,NaN,NaN

In [ ]:
DB_Clients = DB.drop(DB.columns[-5:],axis=1)
DB_Clients

#DL=['deleted','deleted_at','index']
DL=['index']

DB_Clients2 = DB_Clients.drop(DL,axis=1)
DB_Clients2

,id,deleted,deleted_at,info
0,1LeuTEU1OaTbPIDjbkfa2LdHJ2m2,0.0,NaN,"{'dailyRevenue': 0, 'date_reinit_ticket': '13/..."
1,1YUuyZj3vaguDV6kniXkjZHGsVJ3,0.0,NaN,"{'dailyRevenue': 0, 'date_reinit_ticket': '13/..."
2,1fdugKSBzPdBlloqLvtlzHhfKZ22,0.0,NaN,"{'dailyRevenue': 0, 'date_reinit_ticket': '14/..."
3,1lHIQ4SKtgdB097iGGt2cSiNxr92,1.0,24-03-2022,"{'dailyRevenue': 0, 'date_reinit_ticket': '24/..."
4,1wkiFE5YD3fxqTICRHJyGRoCs3k2,0.0,NaN,"{'dailyRevenue': 0, 'date_reinit_ticket': '14/..."
...,...,...,...,...
147,yPFnCPwL8dNnIvz0PzbKRwUOAfF2,1.0,27-12-2021,"{'date_reinit_ticket': '03/08/2021', 'has_tabl..."
148,yrtyvXC2bkVtAW6REaBy1MRMUg73,0.0,NaN,"{'dailyRevenue': 0, 'date_reinit_ticket': '13/..."
149,ywAv0kkVVifXpe108MhktRUePUH3,1.0,27-12-2021,"{'dailyRevenue': 0, 'date_reinit_ticket': '29/..."
150,z6g3Pjyf6PPLhQb9XhUg7JOeoty2,0.0,NaN,"{'currency': 'TND', 'date_reinit_ticket': '07/..."
151,zNRmMJOGbre7RoMLaE5vDjvWVmm1,0.0,NaN,"{'dailyRevenue': 0, 'date_reinit_ticket': '08/..."

In [ ]:
j=0
for i in DB_Clients2['info'] :
   DB_Clients2['info'][j]= ast.literal_eval(i)
   j+=1
type( DB_Clients2['info'][2])

<ipython-input-230-db3875d2497f>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DB_Clients2['info'][j]= ast.literal_eval(i)

dict

In [ ]:
Clients=pd.json_normalize(json.loads(DB_Clients2.to_json(orient="records")))
Clients

,id,deleted,deleted_at,info.dailyRevenue,info.date_reinit_ticket,info.has_tables,info.name,info.opening_time,info.paper_cutter,info.print_ticket,...,info.state.iso2,info.state.latitude,info.state.longitude,info.state.name,info.state.updated_at,info.state.wikiDataId,info.cashless_access,info.cashless_access_ws,info.date_reinit_kitchen,info.isMultiTerminal
0,1LeuTEU1OaTbPIDjbkfa2LdHJ2m2,0.0,None,0.0,13/07/2022,True,ILIADE BAR 1,05:00,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1YUuyZj3vaguDV6kniXkjZHGsVJ3,0.0,None,0.0,13/07/2022,False,THE GRILL,06:00,False,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1fdugKSBzPdBlloqLvtlzHhfKZ22,0.0,None,0.0,14/07/2022,True,MISK,05:00,False,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1lHIQ4SKtgdB097iGGt2cSiNxr92,1.0,24-03-2022,0.0,24/03/2022,True,STOCK TEST,06:00,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1wkiFE5YD3fxqTICRHJyGRoCs3k2,0.0,None,0.0,14/07/2022,True,365 CLUB CAFE,07:00,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,yPFnCPwL8dNnIvz0PzbKRwUOAfF2,1.0,27-12-2021,NaN,03/08/2021,True,BAIA TEST,05:00,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148,yrtyvXC2bkVtAW6REaBy1MRMUg73,0.0,None,0.0,13/07/2022,True,BAR CENTRAL CWM,05:00,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149,ywAv0kkVVifXpe108MhktRUePUH3,1.0,27-12-2021,0.0,29/05/2021,NaN,CAFE'IN,05:00,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150,z6g3Pjyf6PPLhQb9XhUg7JOeoty2,0.0,None,NaN,07/07/2023,True,590,09:09,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
151,zNRmMJOGbre7RoMLaE5vDjvWVmm1,0.0,None,0.0,08/01/2022,True,Chocolat Test,06:00,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Data Exploration ( Full DB )

In [ ]:
Clients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Data columns (total 78 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   id                            152 non-null    object
 1   deleted                       150 non-null    float64
 2   deleted_at                    40 non-null     object
 3   info.dailyRevenue             119 non-null    float64
 4   info.date_reinit_ticket       151 non-null    object
 5   info.has_tables               113 non-null    object
 6   info.name                     152 non-null    object
 7   info.opening_time             152 non-null    object
 8   info.paper_cutter             152 non-null    bool
 9   info.print_ticket             111 non-null    object
 10  info.shop_type_flag           152 non-null    object
 11  info.shop_type_name           152 non-null    object
 12  info.ticket_number            151 non-null    float64
 13  info.arabsoft_interfacing     2 non-null      object
 14  info.checkout_code            3 non-null      object
 15  info.currency                 5 non-null      object
 16  info.drinks_code              3 non-null      object
 17  info.food_code                3 non-null      object
 18  info.hotel_code               3 non-null      object
 19  info.konnectId                1 non-null      object
 20  info.others_code              3 non-null      object
 21  info.support_kitchen          6 non-null      object
 22  info.url                      1 non-null      object
 23  info.codeHotel                5 non-null      object
 24  info.codePrestation           5 non-null      object
 25  info.profile                  2 non-null      object
 26  info.city.country_code        1 non-null      object
 27  info.city.country_id          1 non-null      float64
 28  info.city.created_at          1 non-null      object
 29  info.city.flag                1 non-null      float64
 30  info.city.id                  1 non-null      float64
 31  info.city.latitude            1 non-null      object
 32  info.city.longitude           1 non-null      object
 33  info.city.name                1 non-null      object
 34  info.city.state_code          1 non-null      object
 35  info.city.state_id            1 non-null      float64
 36  info.city.updated_at          1 non-null      object
 37  info.city.wikiDataId          1 non-null      object
 38  info.country.capital          1 non-null      object
 39  info.country.created_at       1 non-null      object
 40  info.country.currency         1 non-null      object
 41  info.country.currency_name    1 non-null      object
 42  info.country.currency_symbol  1 non-null      object
 43  info.country.emoji            1 non-null      object
 44  info.country.emojiU           1 non-null      object
 45  info.country.flag             1 non-null      float64
 46  info.country.id               1 non-null      float64
 47  info.country.iso2             1 non-null      object
 48  info.country.iso3             1 non-null      object
 49  info.country.latitude         1 non-null      object
 50  info.country.longitude        1 non-null      object
 51  info.country.name             1 non-null      object
 52  info.country.native           1 non-null      object
 53  info.country.numeric_code     1 non-null      object
 54  info.country.phonecode        1 non-null      object
 55  info.country.region           1 non-null      object
 56  info.country.subregion        1 non-null      object
 57  info.country.timezones        1 non-null      object
 58  info.country.tld              1 non-null      object
 59  info.country.translations     1 non-null      object
 60  info.country.updated_at       1 non-null      object
 61  info.country.wikiDataId       1 non-null      object
 62  info.state.country_code       1 non-null      object
 63  info.state.country_id         1 non-null      float64
 64  info.state.created_at         1 non-null      object
 65  info.state.fips_code          1 non-null      object
 66  info.state.flag               1 non-null      float64
 67  info.state.id                 1 non-null      float64
 68  info.state.iso2               1 non-null      object
 69  info.state.latitude           1 non-null      object
 70  info.state.longitude          1 non-null      object
 71  info.state.name               1 non-null      object
 72  info.state.updated_at         1 non-null      object
 73  info.state.wikiDataId         1 non-null      object
 74  info.cashless_access          1 non-null      object
 75  info.cashless_access_ws       1 non-null      object
 76  info.date_reinit_kitchen      1 non-null      object
 77  info.isMultiTerminal          1 non-null      object
dtypes: bool(1), float64(12), object(65)
memory usage: 91.7+ KB

In [ ]:
Clients.describe()

,deleted,info.dailyRevenue,info.ticket_number,info.city.country_id,info.city.flag,info.city.id,info.city.state_id,info.country.flag,info.country.id,info.state.country_id,info.state.flag,info.state.id
count,150.000000,119.0,151.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
mean,0.260000,0.0,19.370861,224.0,1.0,106929.0,2558.0,1.0,224.0,224.0,1.0,2558.0
std,0.440104,0.0,48.681087,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,0.0,0.000000,224.0,1.0,106929.0,2558.0,1.0,224.0,224.0,1.0,2558.0
25%,0.000000,0.0,0.000000,224.0,1.0,106929.0,2558.0,1.0,224.0,224.0,1.0,2558.0
50%,0.000000,0.0,2.000000,224.0,1.0,106929.0,2558.0,1.0,224.0,224.0,1.0,2558.0
75%,1.000000,0.0,14.000000,224.0,1.0,106929.0,2558.0,1.0,224.0,224.0,1.0,2558.0
max,1.000000,0.0,369.000000,224.0,1.0,106929.0,2558.0,1.0,224.0,224.0,1.0,2558.0

In [ ]:
Clients.head()

,id,deleted,deleted_at,info.dailyRevenue,info.date_reinit_ticket,info.has_tables,info.name,info.opening_time,info.paper_cutter,info.print_ticket,...,info.state.iso2,info.state.latitude,info.state.longitude,info.state.name,info.state.updated_at,info.state.wikiDataId,info.cashless_access,info.cashless_access_ws,info.date_reinit_kitchen,info.isMultiTerminal
0,1LeuTEU1OaTbPIDjbkfa2LdHJ2m2,0.0,None,0.0,13/07/2022,True,ILIADE BAR 1,05:00,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1YUuyZj3vaguDV6kniXkjZHGsVJ3,0.0,None,0.0,13/07/2022,False,THE GRILL,06:00,False,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1fdugKSBzPdBlloqLvtlzHhfKZ22,0.0,None,0.0,14/07/2022,True,MISK,05:00,False,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1lHIQ4SKtgdB097iGGt2cSiNxr92,1.0,24-03-2022,0.0,24/03/2022,True,STOCK TEST,06:00,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1wkiFE5YD3fxqTICRHJyGRoCs3k2,0.0,None,0.0,14/07/2022,True,365 CLUB CAFE,07:00,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Clients = Clients.drop(Clients.columns[-51:],axis=1)
Clients

,id,deleted,deleted_at,info.dailyRevenue,info.date_reinit_ticket,info.has_tables,info.name,info.opening_time,info.paper_cutter,info.print_ticket,...,info.food_code,info.hotel_code,info.konnectId,info.others_code,info.support_kitchen,info.url,info.codeHotel,info.codePrestation,info.profile,info.city.country_code
0,1LeuTEU1OaTbPIDjbkfa2LdHJ2m2,0.0,None,0.0,13/07/2022,True,ILIADE BAR 1,05:00,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1YUuyZj3vaguDV6kniXkjZHGsVJ3,0.0,None,0.0,13/07/2022,False,THE GRILL,06:00,False,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1fdugKSBzPdBlloqLvtlzHhfKZ22,0.0,None,0.0,14/07/2022,True,MISK,05:00,False,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1lHIQ4SKtgdB097iGGt2cSiNxr92,1.0,24-03-2022,0.0,24/03/2022,True,STOCK TEST,06:00,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1wkiFE5YD3fxqTICRHJyGRoCs3k2,0.0,None,0.0,14/07/2022,True,365 CLUB CAFE,07:00,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,yPFnCPwL8dNnIvz0PzbKRwUOAfF2,1.0,27-12-2021,NaN,03/08/2021,True,BAIA TEST,05:00,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148,yrtyvXC2bkVtAW6REaBy1MRMUg73,0.0,None,0.0,13/07/2022,True,BAR CENTRAL CWM,05:00,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149,ywAv0kkVVifXpe108MhktRUePUH3,1.0,27-12-2021,0.0,29/05/2021,NaN,CAFE'IN,05:00,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150,z6g3Pjyf6PPLhQb9XhUg7JOeoty2,0.0,None,NaN,07/07/2023,True,590,09:09,True,NaN,...,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN
151,zNRmMJOGbre7RoMLaE5vDjvWVmm1,0.0,None,0.0,08/01/2022,True,Chocolat Test,06:00,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
Clients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         152 non-null    object
 1   deleted                    150 non-null    float64
 2   deleted_at                 40 non-null     object
 3   info.dailyRevenue          119 non-null    float64
 4   info.date_reinit_ticket    151 non-null    object
 5   info.has_tables            113 non-null    object
 6   info.name                  152 non-null    object
 7   info.opening_time          152 non-null    object
 8   info.paper_cutter          152 non-null    bool
 9   info.print_ticket          111 non-null    object
 10  info.shop_type_flag        152 non-null    object
 11  info.shop_type_name        152 non-null    object
 12  info.ticket_number         151 non-null    float64
 13  info.arabsoft_interfacing  2 non-null      object
 14  info.checkout_code         3 non-null      object
 15  info.currency              5 non-null      object
 16  info.drinks_code           3 non-null      object
 17  info.food_code             3 non-null      object
 18  info.hotel_code            3 non-null      object
 19  info.konnectId             1 non-null      object
 20  info.others_code           3 non-null      object
 21  info.support_kitchen       6 non-null      object
 22  info.url                   1 non-null      object
 23  info.codeHotel             5 non-null      object
 24  info.codePrestation        5 non-null      object
 25  info.profile               2 non-null      object
 26  info.city.country_code     1 non-null      object
dtypes: bool(1), float64(3), object(23)
memory usage: 31.1+ KB

In [ ]:
Clients = Clients.drop(Clients.columns[-14:],axis=1)
Clients

,id,deleted,deleted_at,info.dailyRevenue,info.date_reinit_ticket,info.has_tables,info.name,info.opening_time,info.paper_cutter,info.print_ticket,info.shop_type_flag,info.shop_type_name,info.ticket_number
0,1LeuTEU1OaTbPIDjbkfa2LdHJ2m2,0.0,None,0.0,13/07/2022,True,ILIADE BAR 1,05:00,True,True,restaurant,Restaurant,8.0
1,1YUuyZj3vaguDV6kniXkjZHGsVJ3,0.0,None,0.0,13/07/2022,False,THE GRILL,06:00,False,True,restaurant,Restaurant,1.0
2,1fdugKSBzPdBlloqLvtlzHhfKZ22,0.0,None,0.0,14/07/2022,True,MISK,05:00,False,True,restaurant,Restaurant,21.0
3,1lHIQ4SKtgdB097iGGt2cSiNxr92,1.0,24-03-2022,0.0,24/03/2022,True,STOCK TEST,06:00,True,True,restaurant,Restaurant,8.0
4,1wkiFE5YD3fxqTICRHJyGRoCs3k2,0.0,None,0.0,14/07/2022,True,365 CLUB CAFE,07:00,True,True,restaurant,Restaurant,151.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,yPFnCPwL8dNnIvz0PzbKRwUOAfF2,1.0,27-12-2021,NaN,03/08/2021,True,BAIA TEST,05:00,True,NaN,restaurant,Restaurant,0.0
148,yrtyvXC2bkVtAW6REaBy1MRMUg73,0.0,None,0.0,13/07/2022,True,BAR CENTRAL CWM,05:00,True,True,restaurant,Restaurant,0.0
149,ywAv0kkVVifXpe108MhktRUePUH3,1.0,27-12-2021,0.0,29/05/2021,NaN,CAFE'IN,05:00,False,NaN,restaurant,Restaurant,0.0
150,z6g3Pjyf6PPLhQb9XhUg7JOeoty2,0.0,None,NaN,07/07/2023,True,590,09:09,True,NaN,restaurant,Restaurant,0.0
151,zNRmMJOGbre7RoMLaE5vDjvWVmm1,0.0,None,0.0,08/01/2022,True,Chocolat Test,06:00,True,NaN,restaurant,Restaurant,2.0

In [ ]:
Clients = Clients.rename(columns={"info.dailyRevenue"	: "dailyRevenue"," info.date_reinit_ticket" : "date_reinit_ticket",	"info.has_tables" : "has_tables",	"info.name" : "name",	"info.opening_time" : "opening_time",	"info.paper_cutter" : "paper_cutter",	"info.print_ticket" : "print_ticket",	"info.shop_type_flag" :"shop_type_flag", "info.shop_type_name" : "shop_type_name",	"info.ticket_number" : "ticket_number"})

# Data Visualization

In [ ]:
print(Clients.deleted.value_counts())

0.0    111
1.0     39
Name: deleted, dtype: int64

In [ ]:
Clients.columns

Index(['id', 'deleted', 'deleted_at', 'dailyRevenue',
       'info.date_reinit_ticket', 'has_tables', 'name', 'opening_time',
       'paper_cutter', 'print_ticket', 'shop_type_flag', 'shop_type_name',
       'ticket_number'],
      dtype='object')

In [ ]:
for col in Clients.columns :
  print(f'{col} : \n {Clients[col].value_counts()} \n \n')

id :
 30YFAYimEDedmiybuL7iny2YrEz2    2
1LeuTEU1OaTbPIDjbkfa2LdHJ2m2    1
iWfcpugFf1ZWE7dYprJlxxGnH293    1
gkJn7eYTtDNIOfLxF2JuLjeO5Ag2    1
h0hvcfjN7YX6WgRWcoOrGwzZQzC3    1
                               ..
IJFCwX87WpWuHuSpAEXgOIZ2ZUx1    1
IVxuNCiIP8YVKCSHvFkEzKz44TU2    1
Idtx9P8iVyM2vUOvBtHvE24OH7w2    1
JKHDEfPAfUhvkPUztKdlKn3BtG32    1
zNRmMJOGbre7RoMLaE5vDjvWVmm1    1
Name: id, Length: 151, dtype: int64


deleted :
 0.0    111
1.0     39
Name: deleted, dtype: int64


deleted_at :
 27-12-2021    17
23-06-2021     3
26-07-2021     2
04-10-2021     2
25-01-2022     2
08-07-2021     2
24-03-2022     1
26-10-2021     1
01-11-2021     1
02-04-2021     1
17-05-2021     1
05-07-2022     1
25-06-2021     1
16-12-2021     1
09-01-2023     1
07-12-2021     1
08-06-2021     1
17-06-2021     1
Name: deleted_at, dtype: int64


dailyRevenue :
 0.0    119
Name: dailyRevenue, dtype: int64


info.date_reinit_ticket :
 13/07/2022    32
14/07/2022    21
18/06/2021    15
08/07/2022     6
18/06/2022     4
              ..
26/06/2021     1
10/05/2022     1
21/10/2021     1
08/07/2021     1
08/01/2022     1
Name: info.date_reinit_ticket, Length: 67, dtype: int64


has_tables :
 True     95
False    18
Name: has_tables, dtype: int64


name :
 ENTREPROS COFFEE      2
Samar shop test       2
MINIONS COFFEE OLD    2
ILIADE BAR 1          1
MENU                  1
                     ..
BEACH BAR             1
AFRICANA BAR 3        1
CAFE MAURE            1
POS TEST              1
Chocolat Test         1
Name: name, Length: 149, dtype: int64


opening_time :
 05:00    86
06:00    20
08:00    16
07:00    13
04:00     4
10:00     3
00:00     1
02:00     1
10:30     1
08:30     1
12:00     1
09:00     1
07:30     1
05:30     1
09:26     1
09:09     1
Name: opening_time, dtype: int64


paper_cutter :
 False    86
True     66
Name: paper_cutter, dtype: int64


print_ticket :
 True     104
False      7
Name: print_ticket, dtype: int64


shop_type_flag :
 restaurant    141
fast_food       7
boutique        2
beach_bar       1
pizzeria        1
Name: shop_type_flag, dtype: int64


shop_type_name :
 Restaurant    141
Fast Food       7
Boutique        2
Beach Bar       1
Pizzeria        1
Name: shop_type_name, dtype: int64


ticket_number :
 0.0      62
1.0      13
2.0       9
8.0       7
3.0       4
6.0       4
4.0       4
5.0       4
7.0       3
56.0      2
22.0      2
16.0      2
21.0      2
14.0      2
26.0      1
49.0      1
17.0      1
110.0     1
143.0     1
82.0      1
89.0      1
23.0      1
369.0     1
12.0      1
29.0      1
106.0     1
19.0      1
295.0     1
124.0     1
111.0     1
128.0     1
69.0      1
57.0      1
24.0      1
48.0      1
172.0     1
31.0      1
25.0      1
35.0      1
18.0      1
9.0       1
43.0      1
27.0      1
151.0     1
46.0      1
Name: ticket_number, dtype: int64

In [ ]:
drop_List = ['info.date_reinit_ticket','paper_cutter','print_ticket','shop_type_name']

Clients = Clients.drop(drop_List,axis=1)

In [ ]:
Clients

,id,deleted,deleted_at,dailyRevenue,has_tables,name,opening_time,shop_type_flag,ticket_number
0,1LeuTEU1OaTbPIDjbkfa2LdHJ2m2,0.0,None,0.0,True,ILIADE BAR 1,05:00,restaurant,8.0
1,1YUuyZj3vaguDV6kniXkjZHGsVJ3,0.0,None,0.0,False,THE GRILL,06:00,restaurant,1.0
2,1fdugKSBzPdBlloqLvtlzHhfKZ22,0.0,None,0.0,True,MISK,05:00,restaurant,21.0
3,1lHIQ4SKtgdB097iGGt2cSiNxr92,1.0,24-03-2022,0.0,True,STOCK TEST,06:00,restaurant,8.0
4,1wkiFE5YD3fxqTICRHJyGRoCs3k2,0.0,None,0.0,True,365 CLUB CAFE,07:00,restaurant,151.0
...,...,...,...,...,...,...,...,...,...
147,yPFnCPwL8dNnIvz0PzbKRwUOAfF2,1.0,27-12-2021,NaN,True,BAIA TEST,05:00,restaurant,0.0
148,yrtyvXC2bkVtAW6REaBy1MRMUg73,0.0,None,0.0,True,BAR CENTRAL CWM,05:00,restaurant,0.0
149,ywAv0kkVVifXpe108MhktRUePUH3,1.0,27-12-2021,0.0,NaN,CAFE'IN,05:00,restaurant,0.0
150,z6g3Pjyf6PPLhQb9XhUg7JOeoty2,0.0,None,NaN,True,590,09:09,restaurant,0.0
151,zNRmMJOGbre7RoMLaE5vDjvWVmm1,0.0,None,0.0,True,Chocolat Test,06:00,restaurant,2.0

In [ ]:
print(list(Clients['name']))

['ILIADE BAR 1', 'THE GRILL', 'MISK', 'STOCK TEST', '365 CLUB CAFE', 'Siwar Shop', 'No info 2', 'MINIONS COFFEE OLD', 'SNACK BAR CWM', 'CHEZ ARBI', 'MINIONS COFFEE', 'CI GUSTA KRAM', 'PASHA', 'PENELOPE BAR 3', 'ART CULTURE STUDIO', 'MANAR BEACH BAR', 'W Coffee Shop', 'VENUS BAR 3', 'WLED LAHNINA', 'PENELOPE BAR 1', 'THE CORNER', 'BELGIAN FRIES', 'KHIMA - TOZEUR', 'POS TEST 2', 'ALI BABA', 'PENELOPE BAR 2', 'BAIA BEACH', 'ROOM SERVICE', 'Tmakhmikha Beb Mnara', 'SAM SHOP TEST', 'BENT EL BEY', 'RR COFFEE', 'SHOP TEST', 'MANAR POS 5', 'baya shop', 'F6L TEST', 'Samar shop test', 'SKANES LOBBY BAR', 'PBP DJERBA BAR 2', 'shop_test2', 'AFRICANA BAR 1', 'CAFE YACINE', 'IN CORNER', 'MIMOSA PARK', 'MANAR POS 7', 'COTHINKING', 'BAIA ROOF TOP', 'ITHAQUE', 'NEW FOOD GAFSA', 'KAYU SUSHI', 'ARDOISE', 'BEACH BAR', 'Samar shop test', 'AFRICANA BAR 3', 'CAFE MAURE', 'POS TEST', 'ENTREPROS COFFEE', 'Pï¿½tisserie  EL BECHA', 'PENELOPE BAR 7', 'VENUS BAR 2', 'SHAYEN', 'MAYA - TOZEUR', 'HELMI SPORT', 'POSPOSTEST', 'TMAHMICHA', 'CONCORDE', 'Express Carthage Land', 'PBP DJERBA BAR 1', 'Cafï¿½ 18 ï¿½', 'SPA - TOZEUR', 'LE BATEAU', 'LUPIN', 'tmakhmikha', 'POS Test 2', 'test04-08', 'OOREDOO STORE', 'MANAR SPORT BAR', 'SKANES STEAK HOUSE', 'KANO BEACH', 'PBP DJERBA BAR 4', 'SAMAAR SHOP TEST', 'MANAR POS 6', 'Sheherazade Beach Bar', 'PBP DJERBA BAR 5', 'Cook Up', 'RECEPTION MAGIC TOURS', 'INSTAFOOD', 'SKANES DOWN TOWN', 'DA POUPï¿½E', 'shoptest07', 'Sheherazade Pool Bar', 'PENELOPE BAR 6', 'DISCOTHEQUE CWM', 'ENTREPROS COFFEE', 'NEPTUNE', 'PENELOPE BAR 4', 'YADIS BAR 1', 'Sheherazade Bar Plage', 'TRIADE', 'NEW FOOD BIZERTE', "CAFE L'OASIS", 'Test no info', 'CABINE MASSAGE SKANES', 'test', 'Co-Chefs RESTO', 'MENU', 'RESTAURANT CWM', 'chez papi', 'FAST-FOOD TEST', 'SHODAI', 'Nostra Villa', 'EL KOOCHA', 'YOW', 'Sheherazade Beach Bar 2', 'PBP DJERBA BAR 3', "FLAM'S FOOD", 'MANAR RECEPTION', 'The Guest', 'SKANES CAFï¿½ MAURE', "LilO's", 'Flume Ride', 'Sheherazade Bar', 'SAMAR SHOP TEST', 'shoptest25-01', 'DAR  ASSAFA', 'NEW FOOD LAC2', 'MINIONS COFFEE OLD', 'CABINE CORDAGE SKANES', 'MANAR SNACK', 'AFRICANA BAR 2', 'BEN ZOUITA CAFE', 'ILIADE BAR 2', 'PENELOPE BAR 5', 'DJERID - CHOTT', 'testregion1', 'LE PRï¿½SIDENT', 'POINT BAR', 'BAIA BAR', 'Co-Chefs COFFEE', 'Histoire De Gï¿½uts', 'COFFEE M9', 'HOT BOX', 'A LA SALLALA', 'CRAZY FOOD', 'MEDUSA', 'VENUS LOBBY BAR', 'LA GUIMAUVE', 'BAIA TEST', 'BAR CENTRAL CWM', "CAFE'IN", '590', 'Chocolat Test']

In [ ]:
sns.countplot(data = df, x = 'deleted')

In [ ]:
#A quick barplot
plt.figure(figsize=(20, 4))
sns.countplot(data = df, x = 'category', order=df.category.value_counts().index)

In [ ]:
plt.figure(figsize=(10, 6))
sns.countplot(data = df, y = 'city', order = df.city.value_counts().index)

In [ ]:
#Scatter plot price against the size, with the type as a hue
plt.figure(figsize=(10, 7))
sns.scatterplot(data = df , x="size", y="price", hue="type")

# Exporting Data

In [ ]:
#Clients.to_excel('Clients.xlsx')