In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import seaborn as sns
import pandas as pd
import json
import ast

In [ ]:
do = pd.read_excel("/content/Discrete_Drinks.xlsx")

In [ ]:
do

,index,date,delivery,total,placement,article.famille_name,article.price,article.product_name,article.quantity
0,0,29/03/2023 08:51,0,5.4,NONE,Coffee,0.9,Supp caramel,1
1,1,29/03/2023 08:51,0,5.4,NONE,Coffee,0.9,Supp caramel,1
2,2,29/03/2023 08:51,0,5.4,NONE,Coffee,0.9,Supp caramel,1
3,3,29/03/2023 08:51,0,5.4,NONE,Coffee,0.9,Supp caramel,1
4,4,29/03/2023 08:51,0,5.4,NONE,Coffee,0.9,Supp caramel,1
...,...,...,...,...,...,...,...,...,...
316,316,08/08/2023 12:58,0,12.0,NONE,Jus,5.0,Citronnade,2
317,317,08/08/2023 12:58,0,12.0,NONE,Jus,1.0,Jus d'Orange,2
318,318,08/08/2023 13:00,0,25.0,NONE,Jus,5.0,Citronnade,5
319,319,08/08/2023 13:04,0,11.0,NONE,Jus,5.0,Citronnade,2
320,320,08/08/2023 13:04,0,11.0,NONE,Jus,1.0,Jus d'Orange,1

In [ ]:
from pandas.core.tools.datetimes import to_datetime
do['date'] = to_datetime(do['date'])

In [ ]:
#do['date'][3]
type(do.loc[0]) # series
do.loc[0]['date'].hour
#t = pd.to_datetime((1,3,2023,4,15),"%d/%m/%Y %H:%M ")
#t = pd.to_datetime((1, 3, 2023, 4, 15), format="%d/%m/%Y %H:%M")

8

Create 6 margins

In [ ]:
def DataDiscretisation(do):
  Converted_Date = []
  for l in range(len(do)) :
    #Discretisation days of the month
    if (do.loc[l]['date'].day in range(1,6))  :
      day='01'
    elif (do.loc[l]['date'].day in range(6,11)) :
      day='06'
    elif (do.loc[l]['date'].day in range(11,16)) :
      day='11'
    elif (do.loc[l]['date'].day in range(16,21)) :
      day='16'
    elif (do.loc[l]['date'].day in range(21,26)) :
      day='21'
    elif (do.loc[l]['date'].day in range(26,31)) :
      day='26'

    # Discretisation hours of the day
    if (do.loc[l]['date'].hour in range(4,10))  : hour = '04'
    elif (do.loc[l]['date'].hour in range(10,12)) : hour = '10'
    elif (do.loc[l]['date'].hour in range(12,15)) : hour = '12'
    elif (do.loc[l]['date'].hour in range(15,18)) : hour = '15'
    elif (do.loc[l]['date'].hour in range(18,00)) : hour = '18'
    elif (do.loc[l]['date'].hour in range(0,4)) : hour = '00'

    m = str(do.loc[l]["date"].month)
    if len(m) ==1 :
      m='0'+m
    New_Date = day +'/'+ m +'/2023 '+ hour +':00'

    Converted_Date.append(pd.to_datetime(New_Date,format='%d/%m/%Y %H:%M'))

  do['Converted_Date'] = Converted_Date
  return 'success'
  #return Converted_Date

DataDiscretisation(do)

'success'

In [ ]:
def DataDiscretisation(do):
  Converted_Date = []
  for l in range(len(do)) :
    #Discretisation days of the month
    if (do.loc[l]['date'].day in range(1,3))  :
      day='01'
    elif (do.loc[l]['date'].day in range(3,5)) :
      day='03'
    elif (do.loc[l]['date'].day in range(5,7)) :
      day='05'
    elif (do.loc[l]['date'].day in range(7,9)) :
      day='07'
    elif (do.loc[l]['date'].day in range(9,11)) :
      day='09'
    elif (do.loc[l]['date'].day in range(11,13)) :
      day='11'
    elif (do.loc[l]['date'].day in range(13,15)) :
      day='13'
    elif (do.loc[l]['date'].day in range(15,17)) :
      day='15'
    elif (do.loc[l]['date'].day in range(17,19)) :
      day='17'
    elif (do.loc[l]['date'].day in range(19,21)) :
      day='19'
    elif (do.loc[l]['date'].day in range(21,23)) :
      day='21'
    elif (do.loc[l]['date'].day in range(23,25)) :
      day='23'
    elif (do.loc[l]['date'].day in range(25,27)) :
      day='25'
    elif (do.loc[l]['date'].day in range(27,29)) :
      day='27'
    elif (do.loc[l]['date'].day in range(29,31)) :
      day='29'
    elif (do.loc[l]['date'].day == 31) :
      day='31'

    # Discretisation hours of the day
    for i in range(10):
      if do.loc[l]['date'].hour == i : hour = '0'+str(i)
    for i in range(10,24):
      if do.loc[l]['date'].hour == i : hour = str(i)

    m = str(do.loc[l]["date"].month)
    if len(m) ==1 :
      m='0'+m
    New_Date = day +'/'+ m +'/2023 '+ hour +':00'

    Converted_Date.append(pd.to_datetime(New_Date,format='%d/%m/%Y %H:%M'))

  do['Converted_Date'] = Converted_Date
  return 'success'
  #return Converted_Date

DataDiscretisation(do)

'success'

In [ ]:
do

,index,date,delivery,total,placement,article.famille_name,article.price,article.product_name,article.quantity,Converted_Date
0,0,2023-03-29 08:51:00,0,5.4,NONE,Coffee,0.9,Supp caramel,1,2023-03-29 08:00:00
1,1,2023-03-29 08:51:00,0,5.4,NONE,Coffee,0.9,Supp caramel,1,2023-03-29 08:00:00
2,2,2023-03-29 08:51:00,0,5.4,NONE,Coffee,0.9,Supp caramel,1,2023-03-29 08:00:00
3,3,2023-03-29 08:51:00,0,5.4,NONE,Coffee,0.9,Supp caramel,1,2023-03-29 08:00:00
4,4,2023-03-29 08:51:00,0,5.4,NONE,Coffee,0.9,Supp caramel,1,2023-03-29 08:00:00
...,...,...,...,...,...,...,...,...,...,...
316,316,2023-08-08 12:58:00,0,12.0,NONE,Jus,5.0,Citronnade,2,2023-08-07 12:00:00
317,317,2023-08-08 12:58:00,0,12.0,NONE,Jus,1.0,Jus d'Orange,2,2023-08-07 12:00:00
318,318,2023-08-08 13:00:00,0,25.0,NONE,Jus,5.0,Citronnade,5,2023-08-07 13:00:00
319,319,2023-08-08 13:04:00,0,11.0,NONE,Jus,5.0,Citronnade,2,2023-08-07 13:00:00
320,320,2023-08-08 13:04:00,0,11.0,NONE,Jus,1.0,Jus d'Orange,1,2023-08-07 13:00:00

In [ ]:
do = do.drop(['article.famille_name','date'], axis=1)
do = do.drop('placement', axis=1)

1

In [ ]:

'Supp fromage'
'Cornet Escalope'
'Cornet Thon'
'PM. Neptune'
'PM. Margherita'
'PM. Reine'

do['Converted_Date'][7]

Timestamp('2023-03-29 00:00:00')

In [ ]:
def NumberByProduct(do) :
  #Sup_Fr,C_Esc,C_Thon,PM_Nep,PM_Mar,PM_R=[],[],[],[],[],[]
  Sup_caramel,Sup_nutella,Jus_Orange,Citronnade = [0 for i in range(70)],[0 for i in range(70)],[0 for i in range(70)],[0 for i in range(70)]
  Express,Direct,Turc = [0 for i in range(70)],[0 for i in range(70)],[0 for i in range(70)]
  NB_Total_Commandes = []
  NB_Delivery = []
  Total_Quantity = []
  Sum_Revenues = []
  Converted_Date = []

  if do['article.product_name'][0] == 'Supp caramel' : Sup_caramel[0] = 1
  elif do['article.product_name'][0] == 'Supp nutella' : Sup_nutella[0] = 1
  elif do['article.product_name'][0] == 'Jus d\'Orange' : Jus_Orange[0] = 1
  elif do['article.product_name'][0] == 'Citronnade' : Citronnade[0] = 1
  elif do['article.product_name'][0] == 'Express' : Express[0] = 1
  elif do['article.product_name'][0] == 'Direct' : Direct[0] = 1
  elif do['article.product_name'][0] == 'Cafe Turc' : Turc[0] = 1

  l=1
  while l < len(do) :
    Converted_Date.append(do['Converted_Date'][l])
    iCom = 1
    deliv = do['delivery'][l]
    quantity = do['article.quantity'][l]
    Revenues = do['total'][l]

    #print('pass 1 : ',l)

    while (do['Converted_Date'][l] == do['Converted_Date'][l-1]) :
      #print('pass 2 : ',iCom)
      iCom +=1
      deliv += do['delivery'][l]
      quantity += do['article.quantity'][l]
      Revenues += do['total'][l]


      if do['article.product_name'][l] == 'Supp caramel' :
        Sup_caramel[len(NB_Delivery)] += 1
      elif do['article.product_name'][l] == 'Supp nutella' :
        Sup_nutella[len(NB_Delivery)] += 1
      elif do['article.product_name'][l] == 'Jus d\'Orange' :
        Jus_Orange[len(NB_Delivery)] += 1
      elif do['article.product_name'][l] == 'Citronnade' :
        Citronnade[len(NB_Delivery)] += 1
      elif do['article.product_name'][l] == 'Express' :
        Express[len(NB_Delivery)] += 1
      elif do['article.product_name'][l] == 'Direct' :
        Direct[len(NB_Delivery)] += 1
      elif do['article.product_name'][l] == 'Cafe Turc' :
        Turc[len(NB_Delivery)] += 1

      l+=1
      if (l==321) : break
    l+=1

    #Save summary data for new line in group G(x,y) where x: day phase in the month [1..6], y hour phase in the day [1..6]
    NB_Total_Commandes.append(iCom)
    NB_Delivery.append(deliv)
    Total_Quantity.append(quantity)
    Sum_Revenues.append(Revenues)

  dictClean = {'Converted_Date' : Converted_Date, 'Sum_Revenues' : Sum_Revenues,'Total_Quantity' : Total_Quantity, 'NB_Delivery' : NB_Delivery,'NB_Total_Commandes' :NB_Total_Commandes ,
          'Sup_caramel':Sup_caramel,'Sup_nutella':Sup_nutella,'Jus_Orange':Jus_Orange,'Citronnade':Citronnade,'Express':Express,'Direct':Direct,'Turc':Turc}


  # Make all lists same length as that of Converted_Dates to make a DF out of them eventually
  for k,v in dictClean.items() :
    if k not in ['Converted_Date','Total_Quantity','NB_Delivery','NB_Total_Commandes','Sum_Revenues']:
      dictClean[k]=v[:len(Converted_Date)]


  dc = pd.DataFrame(data=dictClean, index=Converted_Date)

  return dc

Clean_Discrete_Drinks = NumberByProduct(do)

In [ ]:
Clean_Discrete_Drinks

,Converted_Date,Sum_Revenues,Total_Quantity,NB_Delivery,NB_Total_Commandes,Sup_caramel,Sup_nutella,Jus_Orange,Citronnade,Express,Direct,Turc
2023-03-29 08:00:00,2023-03-29 08:00:00,32.40,6,0,6,6,0,0,0,0,0,0
2023-03-29 00:00:00,2023-03-29 00:00:00,3.60,4,0,4,3,0,0,0,0,0,0
2023-03-29 22:00:00,2023-03-29 22:00:00,1.80,2,0,2,1,0,0,0,0,0,0
2023-03-29 23:00:00,2023-03-29 23:00:00,270.00,5,0,5,4,0,0,0,0,0,0
2023-04-03 22:00:00,2023-04-03 22:00:00,3.60,2,0,2,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
2023-04-07 09:00:00,2023-04-07 09:00:00,39.64,4,0,4,0,0,0,1,0,0,2
2023-04-07 10:00:00,2023-04-07 10:00:00,26.00,2,0,2,0,0,0,0,0,1,0
2023-08-07 12:00:00,2023-08-07 12:00:00,12.00,2,1,1,0,0,0,0,0,0,0
2023-08-07 12:00:00,2023-08-07 12:00:00,82.00,13,2,6,0,0,3,2,0,0,0
2023-08-07 13:00:00,2023-08-07 13:00:00,33.00,5,0,3,0,0,1,1,0,0,0

# Exporting Data

In [ ]:
Clean_Discrete_Drinks.to_excel("Clean_Discrete_Drinks.xlsx")